### ISSUE TITLE
第一次使用报错

### ISSUE THREAD

**Issue by ladder1984** [sshwsfc/django-xadmin#247]
按照<https://xadmin.readthedocs.org/en/latest/quickstart.html>做的，报错内容如下，请问是哪里的问题？
>Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\core\managem
ent\__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\core\managem
ent\__init__.py", line 354, in execute
    django.setup()
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\__init__.py"
, line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\apps\registr
y.py", line 108, in populate
    app_config.import_models(all_models)
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\apps\config.
py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\xadmin\models.py", line 19, in <module>
    AUTH_USER_MODEL = django.contrib.auth.get_user_model()
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\contrib\auth
\__init__.py", line 136, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\apps\registr
y.py", line 199, in get_model
    self.check_models_ready()
  File "C:\Python27\lib\site-packages\django-1.7.1-py2.7.egg\django\apps\registr
y.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by Ma233** [comment]
如果是用 pip 安装的话，目前 0.5.0 版本不支持 Django1.7 以上版本，退回到 Django1.6.5 可以解决。

**Comment by ElsaHuang** [comment]
django 1.9也有类似的问题额，如果使用编译安装的话
