### ISSUE TITLE
ImportError: No module named related demo运行不起来

### ISSUE THREAD

**Issue by wynnfynn** [sshwsfc/django-xadmin#273]
Hi, 
         可以帮我看看, 这个related为什么已经安装还是找不到, 我把django.db.models.related 更改为django.db.models.fields.related 也不能解决问题
(ve)[root@localhost demo_app]# pip install django-related
Downloading/unpacking django-related
  Downloading django-related-0.0.6.tar.gz
  Running setup.py egg_info for package django-related
    
Installing collected packages: django-related
  Running setup.py install for django-related
    
Successfully installed django-related
Cleaning up...
(ve)[root@localhost demo_app]# python manage.py runserver 0.0.0.0:9000
/root/django-xadmin-master/demo_app/../xadmin/__init__.py:18: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/root/django-xadmin-master/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/root/django-xadmin-master/ve/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/root/django-xadmin-master/ve/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/django-xadmin-master/ve/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/root/django-xadmin-master/demo_app/../xadmin/apps.py", line 13, in ready
    self.module.autodiscover()
  File "/root/django-xadmin-master/demo_app/../xadmin/__init__.py", line 28, in autodiscover
    from xadmin.views import register_builtin_views
  File "/root/django-xadmin-master/demo_app/../xadmin/views/__init__.py", line 2, in <module>
    from base import BaseAdminPlugin, BaseAdminView, CommAdminView, ModelAdminView, filter_hook, csrf_protect_m, BaseAdminObject
  File "/root/django-xadmin-master/demo_app/../xadmin/views/base.py", line 30, in <module>
    from xadmin.util import static, json, vendor, sortkeypicker
  File "/root/django-xadmin-master/demo_app/../xadmin/util.py", line 5, in <module>
    from django.db.models.related import RelatedObject
ImportError: No module named related
(ve)[root@localhost demo_app]#

**Comment by jshpng** [comment]
我也遇到同样问题，Django降到1.7就好了

**Comment by liu1700** [comment]
当前这个版本对Django1.8的支持不太好

**Comment by cupen** [comment]
目前 master 分支只支持django1.7，要用django1.8的话就试试那个1.8的分支吧。
