### ISSUE TITLE
Issue running xadmin

### ISSUE THREAD

**Issue by federicoaaguirre** [sshwsfc/django-xadmin#299]
Hi all,

I'm can't run django admin with xadmin module installed :(

Unhandled exception in thread started by <function wrapper at 0x105ca8488>
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Library/Python/2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/__init__.py", line 1, in <module>
    from xadmin.sites import AdminSite, site
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/sites.py", line 342, in <module>
    site = AdminSite()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/sites.py", line 42, in __init__
    self.check_dependencies()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/sites.py", line 163, in check_dependencies
    from django.contrib.contenttypes.models import ContentType
  File "/Library/Python/2.7/site-packages/django/contrib/contenttypes/models.py", line 161, in <module>
    class ContentType(models.Model):
  File "/Library/Python/2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

Some help? any idea?

**Comment by atyu30** [comment]
(goooke)[user02@dj01 ccs]$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/__init__.py", line 1, in <module>
    from xadmin.sites import AdminSite, site
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/sites.py", line 342, in <module>
    site = AdminSite()
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/sites.py", line 42, in __init__
    self.check_dependencies()
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django_xadmin-0.5.0-py2.7.egg/xadmin/sites.py", line 163, in check_dependencies
    from django.contrib.contenttypes.models import ContentType
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/user02/.virtualenvs/goooke/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by atyu30** [comment]
https://github.com/sshwsfc/xadmin/issues/247

**Comment by singold** [comment]
I've run into this issue myself and solved it by installing django-reversion with pip install django-reversion.

I didn't installed it because it said [OPTION] but it looks like it is required.

Maybe this can help you or someone running into this same issue
